TARGET = libjsonz.so
OBJECTS = jsonz.o jsonz-internal.o jsonz-object.o
HEADERS = jsonz

CC = gcc
LD = $(CC)

CFLAGS = -Wall -fPIC -I. -c

LDFLAGS = -fPIC -shared


all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(LD) $(LDFLAGS) -o $@ $^

install: $(TARGET)
	cp $(TARGET) /usr/lib
	cp -r $(HEADERS) /usr/include

clean:
	rm -f $(OBJECTS) $(TARGET) jsonzprettify

uninstall:
	rm -f /usr/lib/$(TARGET)
	rm -f /usr/include/$(HEADERS)/*

%.o: %.c
	$(CC) $(CFLAGS) $^
